#====================================================================
# First using GitHub Acions for test this service.
# Test tasks is:
# [1] Try to use gitHub Actions.
# [2] Try to Minify js and css files in container before deploy.
# [3] Try more cool stuff =)
#====================================================================

name: testingGitHubActionsDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    
    steps:
      - name: Print-to-console
        run: echo "Starting deploy!"
        
      - name: Print-list-of-files  
        run: ls -la
      
      - uses: actions/checkout@v3
      
      - name: Print-new-list-of-file
        run: ls -la
      
      - name: Print-js
        run: cat js/script.js
