#====================================================================
# First using GitHub Acions for test this service.
# Test tasks is:
# [1] Try to use gitHub Actions.
# [2] Try to Minify js and css files in container before deploy.
# [3] Try more cool stuff =)
#====================================================================

name: testingGitHubActionsDeploy

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # First is build
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Downloading files to container
      - name: Checkout
        uses: actions/checkout@v3
      # Print files
      - name: Print js & css files before
        run: |
              cat js/script.js
              echo "=================================="
              cat css/style.css
      # Print files size
      - name: Print files size
        run: |
              ls -lh 'js'
              ls -lh 'css'
      # Minify files using nizarmah/auto-minify@v2.1
      - name: Minify JS & CSS
        uses: nizarmah/auto-minify@v2.1
        with:
          maxdepth: 2
          #directory: 'js'
          overwrite: true
      # Print files content to ensure that it works
      - name: Print js & css files after
        run: |
              cat js/script.js
              echo "=================================="
              cat css/style.css
      # Print files new size       
      - name: Print files size
        run: |
              ls -lh 'js'
              ls -lh 'css'
      # Next is standart deploy
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Print success message
        run: echo "building completed  successfully!"          
  
  # Next is testing (not using here)
  testing:
    runs-on: ubuntu-latest
    needs: [build]
    strategy: 
      max-parallel: 4
      matrix:
        messages: ["This is message 1", "This is message 2", "This is message 3", "This is message 4"]
    
    steps:
      # Simple test how to use matrix and strategy
      - name: Print messages
        run: echo ${{ matrix.messages }}
      - name: Print message
        run: echo "No tests!"
  
  # Finally deploy! 🚀 🚀 🚀
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Print success message
        run: echo "Deployment completed  successfully!"
